# 5.4 错误

错误与异常的**区别**：

- 错误：可能出现问题的地方出现了问题。比如打开一个文件时失败，这在人们的意料之中。
- 异常：不应该出现问题的地方出现了问题，比如引用了空指针，这在人们的意料之外

因此错误是业务过程的一部分，而异常不是。

与其他语言不同，**Go语言通过使用普通的值而非异常来报告错误**。尽管Go语言有异常机制，但是Go语言的异常只是针对程序bug导致的预料外的错误，而不能作为常规的错误处理方法出现在程序中。

这样做原因是异常会陷入带有错误消息的控制流去处理它，通常会导致预期外的结果：错误会以难以理解的栈跟踪信息报告给最终用户，这些信息大都是关于程序结构方面的而不是简单明了的错误消息。



## 5.4.1 错误处理策略：

**策略1：将错误直接传递下去，使得在子例程中发生的错误变为主调例程的错误**

**策略2：对于不固定或者不可预测的错误，在短暂的间隔后对操作进行重试是合乎情理的，超出一定的重试次数和限定时间后再报错退出**

```go
// 该函数尝试连接URL对应的服务器，在1分钟内使用指数退避策略进行重试，所有的尝试失败后返回错误
func WaitForServer(url string) error {
    const timeout = 1 * time.Minute
    deadline := time.Now().Add(timeout)
    for tries := 0; time.Now().Before(deadline); tries++ {
        _, err := http.Head(url)
        if err == nil {
            return nil // 成功
        }
        log.Printf("server not responding (%s); retrying...", err)
        time.Sleep(time.Second << uint(tries)) // 指数退避策略
    }
    return fmt.Errorf("server %s failed to respond after %s", url, timeout)
}
```

**策略3：如果依旧不能顺利进行下去，调用者能够输出错误然后优雅地停止程序，但一般这样的处理应该留给主程序部分。**

```go
// (In function main. )
if err := WaitForServer(url); err != nil {
    fmt.Fprintf(os.Stderr, "Site is down: %v\n", err)
    os.Exit(1)
}
```

**策略4：在一些错误情况下，只记录错误信息然后程序继续运行**

```go
if err := Ping(); err != nil {
    log.Printf("ping failed: %v; networking disabled", err)
}
```

**策略5：在某些罕见的情况下我们可以直接安全地忽略掉整个日志**



## 5.4.2 文件结束标识：

`io.EOF`

```go
in := bufio.NewReader(os.Stdin)
for{
    r, _, err := in.ReadRune()
    if err == io.EOF{
        break // 结束读取
    }
    if err != nil {
        return fmt.Errorf("read failed: %v", err)
    }
    // ...使用r...
}
```































































